### ISSUE TITLE
how it work

### ISSUE THREAD

**Issue by hamzazzi** [FragJage/MqttEnergeasy#2]
i have energeasy box, how can i use it on home assitant . can you help me please

**Comment by FragJage** [comment]
Hello,
I can you help you if you need some explanations on mqtt messages emitted and received by my MqttEnergeasy daemon.
I can't help you to configure Home assistant, but i think it's possible because i have read that Home assistant can send mqtt message.
For example, if you want open your bed room's shutter you can send
```
{
  "command":"open",
  "parameters":[]
}
```
to topic `energeasy/command/VoletChambre`.
VoletChambre is the label of your device in Energeasy WebSite.
Best regards
